version: '3.8'

services:
  rl_adjust_pose:
    container_name: rl_adjust_pose
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET_IMAGE: ${TARGET_IMAGE:-ubuntu:22.04}
      
    image: rl_adjust_pose_${TARGET_ARCH}:latest
    runtime: ${RUNTIME:-none}
    volumes:
      - "./:/app"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all